
project_id = "ppljsayhwtlogficifar"

[functions.migrate-product-images]
enabled = true
verify_jwt = false

[functions.mpesa-stkpush]
enabled = true
verify_jwt = true

[functions.mpesa-callback]
enabled = true
verify_jwt = true

[functions.paystack-initialize]
enabled = true
verify_jwt = true
import_map = "./functions/paystack-initialize/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/paystack-initialize/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/paystack-initialize/*.html" ]

[functions.paystack-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/paystack-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/paystack-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/paystack-webhook/*.html" ]

[functions.paystack-verify]
enabled = true
verify_jwt = true
import_map = "./functions/paystack-verify/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/paystack-verify/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/paystack-verify/*.html" ]
